version: '3.8'

services:
  # Zabbix MySQL Database
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    depends_on:
      zabbix-db:
        condition: service_healthy
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix-net

  # Zabbix Web Interface
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Kolkata # Change if needed
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  # Zabbix Agent
  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-latest
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
    volumes:
      - zabbix-agent-data:/var/lib/zabbix

  # phpMyAdmin for managing MySQL database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: zabbix-db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      zabbix-db:
        condition: service_healthy
    networks:
      - zabbix-net

networks:
  zabbix-net:
    driver: bridge

volumes:
  zabbix-db-data:
  zabbix-server-data:
  zabbix-agent-data:
